### ISSUE TITLE
Make target network to crawl configurable

### ISSUE THREAD

**Issue by egalano** [INFURA/devp2p-network#8]
Currently, the ChainId, Genesis block hash, and Chain Total Difficulty, and the bootnodes are hardcoded to mainnet. We need to make this configurable to easily crawl any devp2p network like a testnet or private chain.

**Comment by zcstarr** [comment]
Ping here! Awesome tool, I just dropped A PR to make the target network to crawl configurable. I'd love to land these changes, as we'd like to start using this for etclabs as well.
